<#
.SYNOPSIS
  Regenerate Vendored/windows/x64/sqlite3.lib as a tiny import library for Windows'
  built-in SQLite (winsqlite3.dll).

.DESCRIPTION
  SweetCookieKit's Package.swift declares `.linkedLibrary("sqlite3")` UNCONDITIONALLY, so on
  Windows the MSVC linker requires a file named `sqlite3.lib` on its search path — even though
  the Windows MVP reaches no sqlite symbol at runtime (cookie/cost paths are walled/stubbed,
  TD-5; the built exe imports no winsqlite3.dll). See docs/adr/ADR-3 and TD-4.

  Rather than commit a 3 MB static SQLite build, we ship a ~70 KB IMPORT library generated from
  the OS-provided winsqlite3.dll, plus the text `sqlite3.def` it is built from. This script
  regenerates both from source, so the committed lib is fully reproducible (no opaque binary).

  Requires: Visual Studio (Build Tools) with the VC++ x64 workload (dumpbin.exe + lib.exe).
  winsqlite3.dll ships with Windows 10/11 and Server 2019+.

  Usage (from the repo root, no VS Dev shell needed — this script locates the tools):
      pwsh -File Scripts/windows/build-sqlite3-lib.ps1
#>
param(
    [string]$OutDir = (Join-Path $PSScriptRoot "..\..\Vendored\windows\x64"),
    [string]$Dll = (Join-Path $env:WINDIR "System32\winsqlite3.dll")
)
$ErrorActionPreference = "Stop"

if (-not (Test-Path $Dll)) { throw "winsqlite3.dll not found at $Dll (needs Windows 10/11 or Server 2019+)." }

$vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
if (-not (Test-Path $vswhere)) { throw "vswhere.exe not found; install Visual Studio Build Tools (VC++ x64)." }
$vsPath = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
$toolsVer = Get-Content "$vsPath\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt"
$binDir = "$vsPath\VC\Tools\MSVC\$toolsVer\bin\Hostx64\x64"
$dumpbin = Join-Path $binDir "dumpbin.exe"
$lib = Join-Path $binDir "lib.exe"

$OutDir = (Resolve-Path -LiteralPath (New-Item -ItemType Directory -Force -Path $OutDir)).Path
$defPath = Join-Path $OutDir "sqlite3.def"
$libPath = Join-Path $OutDir "sqlite3.lib"

# 1. Enumerate the sqlite3_* symbols the OS DLL exports.
$exports = & $dumpbin /exports $Dll 2>$null
$syms = $exports |
    Select-String '^\s+\d+\s+[0-9A-Fa-f]+\s+[0-9A-Fa-f]+\s+(sqlite3\w*)' |
    ForEach-Object { $_.Matches[0].Groups[1].Value } |
    Sort-Object -Unique
if ($syms.Count -eq 0) { throw "No sqlite3_* exports found in $Dll." }

# 2. Emit the .def (the committed source-of-record for the import lib).
$def = @(
    "; Import library definition for Windows' built-in SQLite (winsqlite3.dll).",
    "; Generated by Scripts/windows/build-sqlite3-lib.ps1 from ``dumpbin /exports``.",
    "; Satisfies SweetCookieKit's unconditional -lsqlite3 on Windows (TD-4 / A2-2).",
    "LIBRARY winsqlite3",
    "EXPORTS"
) + ($syms | ForEach-Object { "    $_" })
Set-Content -LiteralPath $defPath -Value $def -Encoding ascii

# 3. Build the import lib; clean up the .exp byproduct lib.exe leaves behind.
& $lib /def:$defPath /machine:x64 /out:$libPath | Out-Null
Remove-Item (Join-Path $OutDir "sqlite3.exp") -ErrorAction SilentlyContinue

Write-Host ("Wrote {0} ({1} symbols) and {2} ({3:N0} bytes)." -f $defPath, $syms.Count, $libPath, (Get-Item $libPath).Length)
